[RFR] RAT builder rework
sixthedge/cellar pull request #33
Opened 2017-06-05 19:24 UTC by DylanBell

Improves rat-builder functionality and resolves a number of bugs

- Reworks the way that we create and persist choices and questions
- Modifies the way that we set assignment `release_at` and `due_at`
- Reworks the way assessments are synced
- Various client-side validation improvements
- And more!

2017-06-09 19:30 UTC, jamesfid requested changes

2017-06-09 19:30 UTC, jamesfid commented on src/thinkspace/api/thinkspace-casespace/app/models/thinkspace/casespace/assignment.rb
>          return settings['rat']['sync']
This should be a `dig`, especially if using it in the above line.

2017-06-09 19:30 UTC, jamesfid commented on src/thinkspace/api/thinkspace-readiness-assurance/app/models/thinkspace/readiness_assurance/assessment.rb
> +      #after_save :sync_assessments
This line should be removed if we're opting for another method.

2017-06-09 19:30 UTC, jamesfid commented on src/thinkspace/api/thinkspace-readiness-assurance/app/models/thinkspace/readiness_assurance/assessment.rb
> +        assignment = Thinkspace::Casespace::Assignment.find(phase.assignment_id)
phase.thinkspace_casespace_assignment

2017-06-09 19:30 UTC, jamesfid commented on src/thinkspace/api/thinkspace-readiness-assurance/app/models/thinkspace/readiness_assurance/assessment.rb
> +        if assignment.sync_rat?
This is some pretty complicated logic.  Couple of notes:
  * It'd be nice to pull this out into a class that can not pollute the model as much.  There's a lot of nested if/if statements that would be nice to have as separate method (which lends well towards the class abstraction).  For example, you could have a method called `sync_settings` which handles just the settings, etc.
  * I'd use `dig` pretty much everywhere.  It just feels a lot safer than running into `undefined [] for nil` type of error.  I know most of these are scoped out by the if wrappers.

2017-06-09 19:30 UTC, jamesfid commented on src/thinkspace/client/thinkspace-assets/styles/otbl-css/_components.forms.scss
> +		// font-size: 1.15rem;
Remove if not needed.

2017-06-09 19:30 UTC, jamesfid commented on src/thinkspace/client/thinkspace-assets/styles/otbl-css/_helpers.spacing.scss
> +  margin-top: 0 !important;
Did @jcamou add this?  Not a fan of `!important` if it's avoidable.

2017-06-09 19:30 UTC, jamesfid commented on src/thinkspace/client/thinkspace-assets/styles/otbl-css/_objects.checkbox.scss
> +// .checkbox__item {
Removed commented code if not needed.

2017-06-09 19:30 UTC, jamesfid commented on src/thinkspace/client/thinkspace-builder-rat/addon/components/content/question/item/show.coffee
> +    delete:         ->
Make this a one liner like the rest.

2017-06-09 19:30 UTC, jamesfid commented on src/thinkspace/client/thinkspace-builder-rat/addon/items/question.coffee
> +    answer_cs = totem_changeset.create(@,
If you don't have the leading ( you won't need the closing ).

2017-06-09 19:30 UTC, jamesfid commented on src/thinkspace/client/thinkspace-builder-rat/addon/services/manager.coffee
> +      console.log('[DUP] index is ', index)
Remove.

2017-06-09 19:30 UTC, jamesfid commented on src/thinkspace/client/thinkspace-builder-rat/addon/services/manager.coffee
> +      console.log('[DUP] add_at is ', add_at)
Remove.

2017-06-09 19:30 UTC, jamesfid commented on src/thinkspace/client/thinkspace-builder-rat/addon/steps/content.coffee
> +  # trat_question_items: ember.computed 'trat_assessment.questions_with_answers.@each', ->
Remove commented code if not needed.

2017-06-09 19:30 UTC, jamesfid commented on src/thinkspace/client/thinkspace-builder-rat/addon/steps/content.coffee
> +    manager.reorder_item(type, item_obj, -1).then =>
Feels like all of these `manager.reorder_item` calls should be abstracted out.  Lots of repeat code in the `then` handler. Something like:

```
  @manager_reorder(type, obj, offset)
```

2017-06-09 19:30 UTC, jamesfid commented on src/thinkspace/client/thinkspace-builder-rat/addon/steps/details.coffee
> +  # load_assignment_data: ->
Removed if not needed.

2017-06-09 19:30 UTC, jamesfid commented on src/thinkspace/client/thinkspace-builder-rat/addon/steps/details.coffee
> +  # query_team_sets: ->
Remove if not needed.

2017-06-09 19:30 UTC, jamesfid commented on src/thinkspace/client/thinkspace-builder-rat/addon/steps/details.coffee
> +  # select_team_set: (team_set) ->
Remove if not ndeeded.

2017-06-09 19:30 UTC, jamesfid commented on src/thinkspace/client/thinkspace-builder-rat/addon/steps/details.coffee
> +  # initialize_team_set: ->
Remove if not needed.

2017-06-09 19:30 UTC, jamesfid commented on src/thinkspace/client/thinkspace-builder-rat/addon/steps/settings.coffee
> +    scoring_changeset = totem_changeset.create(irat_assessment.get('settings.scoring'),
Some comment as earlier regarding parens.

2017-06-09 19:30 UTC, jamesfid commented on src/thinkspace/client/thinkspace-builder-rat/addon/steps/settings.coffee
> +      #attempted:         [v_integer, v_presence, v_positive],
Remove commented portions if not used.

2017-06-09 19:30 UTC, jamesfid commented on src/thinkspace/client/thinkspace-builder-rat/addon/steps/settings.coffee
> +    changeset.set('show_errors', true)
There is already a function for this, something like `show_errors_on()` - look at the changeset file.

2017-06-09 19:30 UTC, jamesfid commented on src/thinkspace/client/thinkspace-builder-rat/addon/steps/settings.coffee
> +    #changeset = @get('irat_changeset')
Remove.

2017-06-09 22:26 UTC, DylanBell commented on src/thinkspace/api/thinkspace-casespace/app/models/thinkspace/casespace/assignment.rb
>          return settings['rat']['sync']
Addressed

2017-06-09 22:26 UTC, DylanBell commented on src/thinkspace/api/thinkspace-readiness-assurance/app/models/thinkspace/readiness_assurance/assessment.rb
> +      #after_save :sync_assessments
Addressed

2017-06-09 22:27 UTC, DylanBell commented on src/thinkspace/api/thinkspace-readiness-assurance/app/models/thinkspace/readiness_assurance/assessment.rb
> +        assignment = Thinkspace::Casespace::Assignment.find(phase.assignment_id)
Addressed

2017-06-09 22:27 UTC, DylanBell commented on src/thinkspace/client/thinkspace-assets/styles/otbl-css/_components.forms.scss
> +		// font-size: 1.15rem;
Modified by @jcamou

2017-06-09 22:27 UTC, DylanBell commented on src/thinkspace/client/thinkspace-assets/styles/otbl-css/_helpers.spacing.scss
> +  margin-top: 0 !important;
Modified by @jcamou

2017-06-09 22:28 UTC, DylanBell commented on src/thinkspace/client/thinkspace-assets/styles/otbl-css/_objects.checkbox.scss
> +// .checkbox__item {
Modified by @jcamou

2017-06-09 22:28 UTC, DylanBell commented on src/thinkspace/client/thinkspace-builder-rat/addon/components/content/question/item/show.coffee
> +    delete:         ->
Addressed

2017-06-09 22:29 UTC, DylanBell commented on src/thinkspace/client/thinkspace-builder-rat/addon/services/manager.coffee
> +      console.log('[DUP] index is ', index)
Addressed

2017-06-09 22:29 UTC, DylanBell commented on src/thinkspace/client/thinkspace-builder-rat/addon/services/manager.coffee
> +      console.log('[DUP] add_at is ', add_at)
Addressed

2017-06-09 22:30 UTC, DylanBell commented on src/thinkspace/client/thinkspace-builder-rat/addon/steps/content.coffee
> +  # trat_question_items: ember.computed 'trat_assessment.questions_with_answers.@each', ->
Something that's in the process of being modified in the yet-unpushed `feature/rat-desync` branch, to support re-adding the iRAT/tRAT desync capability

2017-06-09 22:31 UTC, jcamou commented on src/thinkspace/client/thinkspace-assets/styles/otbl-css/_helpers.spacing.scss
> +  margin-top: 0 !important;
I've only added !important to the helper classes. Helper classes attributes need to take priority

2017-06-09 22:31 UTC, DylanBell commented on src/thinkspace/client/thinkspace-builder-rat/addon/steps/details.coffee
> +  # query_team_sets: ->
Addressed

2017-06-09 22:31 UTC, DylanBell commented on src/thinkspace/client/thinkspace-builder-rat/addon/steps/details.coffee
> +  # load_assignment_data: ->
Addressed

2017-06-09 22:31 UTC, DylanBell commented on src/thinkspace/client/thinkspace-builder-rat/addon/steps/details.coffee
> +  # select_team_set: (team_set) ->
Addressed

2017-06-09 22:31 UTC, DylanBell commented on src/thinkspace/client/thinkspace-builder-rat/addon/steps/details.coffee
> +  # initialize_team_set: ->
Addressed

2017-06-09 22:31 UTC, DylanBell commented on src/thinkspace/client/thinkspace-builder-rat/addon/steps/settings.coffee
> +      #attempted:         [v_integer, v_presence, v_positive],
Addressed

2017-06-09 22:34 UTC, DylanBell commented on src/thinkspace/client/thinkspace-builder-rat/addon/steps/settings.coffee
> +    #changeset = @get('irat_changeset')
Addressed

2017-06-09 22:47 UTC, DylanBell commented on src/thinkspace/client/thinkspace-builder-rat/addon/steps/settings.coffee
> +    changeset.set('show_errors', true)
Addressed

2017-06-10 02:46 UTC, DylanBell commented on src/thinkspace/client/thinkspace-builder-rat/addon/steps/settings.coffee
> +    scoring_changeset = totem_changeset.create(irat_assessment.get('settings.scoring'),
Addressed

2017-06-10 02:46 UTC, DylanBell commented on src/thinkspace/client/thinkspace-builder-rat/addon/items/question.coffee
> +    answer_cs = totem_changeset.create(@,
Addressed

2017-06-10 03:00 UTC, DylanBell commented on src/thinkspace/api/thinkspace-readiness-assurance/app/models/thinkspace/readiness_assurance/assessment.rb
> +        if assignment.sync_rat?
Reworked by creating the `Thinkspace::ReadinessAssurance::Sync::Assessment` class, which is created by the `Thinkspace::ReadinessAssurance::Assessment` `sync` method. Currently the same `sync` method functionality is simply transplanted to the `Sync::Assessment`

2017-06-10 03:00 UTC, DylanBell commented on src/thinkspace/client/thinkspace-builder-rat/addon/steps/content.coffee
> +    manager.reorder_item(type, item_obj, -1).then =>
Addressed

2017-06-13 14:22 UTC, merged